
version: '3.8'

services:
  citus_coordinator:
    image: citusdata/citus:11.2
    container_name: citus_coordinator
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: historia_clinica
      Citus_Enable: "true"
    depends_on:
      - citus_worker1
      - citus_worker2
    command: ["docker-entrypoint.sh", "postgres", "-c", "wal_level=logical"]
    volumes:
      - coordinator_data:/var/lib/postgresql/data

  citus_worker1:
    image: citusdata/citus:11.2
    container_name: citus_worker1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: historia_clinica
      Citus_Enable: "true"
    command: ["docker-entrypoint.sh", "postgres", "-c", "wal_level=logical"]
    volumes:
      - worker1_data:/var/lib/postgresql/data

  citus_worker2:
    image: citusdata/citus:11.2
    container_name: citus_worker2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: historia_clinica
      Citus_Enable: "true"
    command: ["docker-entrypoint.sh", "postgres", "-c", "wal_level=logical"]
    volumes:
      - worker2_data:/var/lib/postgresql/data

volumes:
  coordinator_data:
  worker1_data:
  worker2_data:
